# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 22:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200)),
                ('tastiness', models.IntegerField(blank=True)),
                ('difficulty', models.IntegerField(blank=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=200)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'Category'), (2, 'Applicance'), (3, 'Cuisine')])),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=420)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile-pics')),
                ('is_active', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('following', models.ManyToManyField(related_name='followers', to='ChillFood.Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('appliances', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('cuisines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('price_min', models.IntegerField(blank=True)),
                ('price_max', models.IntegerField(blank=True)),
                ('has_video', models.BooleanField()),
                ('calories', models.IntegerField(blank=True)),
                ('sort_by', models.IntegerField(choices=[(1, 'Difficulty'), (2, 'Tastiness')], default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('calories', models.IntegerField(blank=True)),
                ('video_link', models.CharField(blank=True, max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('appliances', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('cuisines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='steps')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Recipe'),
        ),
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Person'),
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Recipe'),
        ),
    ]
