# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='appliances',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cuisines',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='display',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='pic',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='step',
            name='step_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Person'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='recipe',
            field=models.ManyToManyField(to='ChillFood.Recipe'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='recipe',
            field=models.ManyToManyField(to='ChillFood.Recipe'),
        ),
        migrations.AddField(
            model_name='category',
            name='recipe',
            field=models.ManyToManyField(to='ChillFood.Recipe'),
        ),
    ]
