# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0004_auto_20161027_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
