# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0004_auto_20161101_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
