# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0006_auto_20161030_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='difficulty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tastiness',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
