# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0008_auto_20161106_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tastiness', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('difficulty', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tastiness',
        ),
    ]
