# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0008_auto_20161028_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='cuisine',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='recipe',
            new_name='recipes',
        ),
    ]
