# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 04:10
from __future__ import unicode_literals

from django.db import migrations, models

def create_categories(apps, schema_editor):
    Category = apps.get_model("ChillFood", "Category")
    
    vegan_category = Category(name='vegan')
    vegan_category.save()

    veg_category = Category(name='veg')
    veg_category.save()

    non_veg_category = Category(name='non-veg')
    non_veg_category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0009_auto_20161028_0404'),
    ]

    operations = [
    	migrations.RunPython(create_categories),
    ]
