# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0011_auto_20161028_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('unit', models.CharField(max_length=200)),
                ('percentOfDailyNeeds', models.DecimalField(decimal_places=3, max_digits=6)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Nutrient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Recipe')),
            ],
        ),
        migrations.AlterField(
            model_name='step',
            name='instruction',
            field=models.CharField(max_length=2000),
        ),
    ]
