# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0012_auto_20161117_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='price_max',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='price_min',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
