# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0012_auto_20161028_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='calories',
        ),
    ]
