# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0013_remove_recipe_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='pic',
        ),
    ]
