# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0014_remove_ingredient_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=200)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('display', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='display',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='Ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFood.Recipe'),
        ),
    ]
