# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 19:00
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings

def create_chillfood_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Person = apps.get_model("ChillFood", "Person")
    
    user = User(username='chillfood', password='chillfood')
    user.save()

    person = Person(user=user, name='ChillFood.com', email='ChillFood@yopmail.com', is_active=True)
    person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0016_auto_20161028_1855'),
    ]

    operations = [
    	migrations.RunPython(create_chillfood_user),
    ]
