# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 08:23
from __future__ import unicode_literals

from django.db import migrations, models

def recreate_categories(apps, schema_editor):
    Category = apps.get_model("ChillFood", "Category")
    Category.objects.all().delete()
    
    vegan_category = Category(name='Vegan')
    vegan_category.save()

    veg_category = Category(name='Veg')
    veg_category.save()

    non_veg_category = Category(name='Non-veg')
    non_veg_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0018_auto_20161030_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Vegan', 'Vegan'), ('Non-veg', 'Non-veg')], max_length=200),
        ),
        migrations.RunPython(recreate_categories),

    ]
