# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0020_recipe_remote_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='location_lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_lon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
