# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0022_auto_20161121_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='ingredient',
            field=models.ManyToManyField(to='ChillFood.Ingredient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
