# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0023_auto_20161202_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set([('recipe', 'ingredient')]),
        ),
    ]
