# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFood', '0024_auto_20161202_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='price_min',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='price',
        ),
    ]
